name: Lint

on:
  pull_request:
    branches:
      - main
      - locale

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: Angular-Hello-World

      - name: Run Angular lint
        run: npm run lint
        working-directory: Angular-Hello-World
